DROP TABLE IF EXISTS rating;
DROP TABLE IF EXISTS tokens;
DROP TABLE IF EXISTS playlist;
DROP TABLE IF EXISTS user;

CREATE TABLE user(
    NAME VARCHAR(26) PRIMARY KEY,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(60) NOT NULL
);

CREATE TABLE playlist(
  LINK VARCHAR(90) PRIMARY KEY,
  USER_NAME VARCHAR(26) NOT NULL,
  FOREIGN KEY (USER_NAME) REFERENCES user(NAME) ON DELETE CASCADE 
);

CREATE TABLE tokens(
    ID INT(11) UNSIGNED AUTO_INCREMENT NOT NULL,
    TOKEN CHAR(60),
    USERID VARCHAR(50) NOT NULL,
    EXPIRES DATE, 
    TIPO ENUM('ACTIVATE', 'REMEMBER', 'RECOVERY') NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE rating(
    TEXT VARCHAR(200) NOT NULL,
    USER_NAME VARCHAR(26) NOT NULL,
    LINK VARCHAR(90) NOT NULL,
    SCORE DECIMAL(2,1) NOT NULL,
    DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (LINK) REFERENCES playlist(LINK) ON DELETE CASCADE,
    FOREIGN KEY (USER_NAME) REFERENCES user(NAME) ON DELETE CASCADE,
    PRIMARY KEY (USER_NAME, LINK)
);

-- Tabla de tokens de usuarios de la API
CREATE TABLE user_tokens (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME INT NOT NULL,
    ACCESS_TOKEN VARCHAR(255) NOT NULL,
    REFRESH_TOKEN VARCHAR(255) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
);

-- REMEMBER es el recuerdame ACTIVATE es activar user y recovery para recuperar psswd en tokens
