-- CREACION DE BASE DE DATOS
-- CREATE DATABASE musicLifeDatabase;

-- BORRADO DE TABLAS
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS PLAYLIST;
DROP TABLE IF EXISTS VALORACION;
-- CREACION DE TABLAS

-- USUARIO
CREATE TABLE USUARIO(
    ID INT(6) PRIMARY KEY,
    NOMBRE VARCHAR(26) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(20) NOT NULL
);

-- PLAYLIST
CREATE TABLE PLAYLIST(
  ID_PL VARCHAR(30) PRIMARY KEY,
  NOMBRE VARCHAR(26) NOT NULL,
  CREADOR_ID INT(6) NOT NULL,
  LINK VARCHAR(20) NOT NULL,
  FOREIGN KEY (CREADOR_ID) REFERENCES USUARIO(ID) ON DELETE CASCADE
  -- FOREIGN KEY (CANCION_ID) REFERENCES CANCIONES(CANCION_ID) ON DELETE CASCADE
);

CREATE TABLE VALORACION(
    VALORACION_ID INT(6) NOT NULL,
    PLAYLIST_ID VARCHAR(30) NOT NULL,
    USUARIO_ID INT(6) NOT NULL,
    PUNTUACION DECIMAL(2,1) NOT NULL,
    COMENTARIO VARCHAR(600),
    FECHA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLIST(ID_PL) ON DELETE CASCADE,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID) ON DELETE CASCADE,
    PRIMARY KEY(VALORACION_ID,PLAYLIST_ID,USUARIO_ID)
);