REM -- 																			BASE DE DATOS - MUSIC DDBB		

REM --					 CREACION DE BASE DE DATOS
--CREATE DATABASE Music_life_DDBB ;
-- Comentado de momento


REM --					 BORRADO DE TABLAS

DROP TABLE USUARIOS CASCADE CONSTRAINT;

REM --					 CREACION DE TABLAS

REM --	USUARIOS
CREATE TABLE USUARIOS(
	ID NUMBER(6) CONSTRAINT PK_USUARIOS PRIMARY KEY,
	NOMBRE VARCHAR2(26) NOT NULL,
	EMAIL VARCHAR2(50) NOT NULL UNIQUE,
	CONTRASENA VARCHAR2(20) NOT NULL
);


REM -- 						BORRADO DE FILAS
DELETE USUARIOS;

REM -- 						CREACION DE FILAS
-- REM DATOS USUARIOS
INSERT INTO USUARIOS (NOMBRE, EMAIL, CONTRASENA) VALUES('Sergio','email1@mail.es','1234');
INSERT INTO USUARIOS (NOMBRE, EMAIL, CONTRASENA) VALUES('Maki','email2@mail.es','1234');
INSERT INTO USUARIOS (NOMBRE, EMAIL, CONTRASENA) VALUES('Miguel','email3@mail.es','1234');
COMMIT;



REM --					 CREACION DE TRIGGERS

REM -- TRIGGER: INCREMENTAR ID USUARIOS AUTOMATICAMENTE - Tal vez no sea necesario, al menos de momento
CREATE SEQUENCE usuarios_secuencia;

CREATE OR REPLACE TRIGGER usuarios_insertados
  BEFORE INSERT ON USUARIOS
  FOR EACH ROW
BEGIN
  SELECT usuarios_secuencia.nextval
  INTO :NEW.ID
  FROM dual;
END;
