CREATE TABLE PLAYLIST(
  ID_PL NUMBER(6) CONSTRAINT PK_PLAYLIST PRIMARY KEY,
  NOMBRE VARCHAR2(26) NOT NULL,
  CREADOR_ID NUMBER(6) NOT NULL,
  LINK VARCHAR2(20) NOT NULL, --AÑADIR UNIQUE Y LINK AL GLOBAL
  CONSTRAINT FK_CREADORID_PLAY FOREIGN KEY (CREADOR_ID) REFERENCES USUARIO(ID) ON DELETE CASCADE,
  --CONSTRAINT FK_CANCIONID_PLAY FOREIGN KEY (CANCION_ID) REFERENCES CANCIONES(CANCION_ID) ON DELETE CASCADE
);

CREATE TABLE USUARIO(
	ID NUMBER(6) CONSTRAINT PK_USUARIO PRIMARY KEY, --SE DEBERIA AÑADIR UNIQUE
	NOMBRE VARCHAR2(26) NOT NULL,
	NICK_NAME VARCHAR(26) NOT NULL UNIQUE,
	EMAIL VARCHAR2(50) NOT NULL UNIQUE,
	CONTRASENA VARCHAR2(20) NOT NULL
);

INSERT INTO USUARIO VALUES(123456,'SERGIO','SERGIO@ADMIN','SERGIO@GMAIL','123456');
INSERT INTO PLAYLIST VALUES (001,'DUA_LIPA',123456,'https://open.spotify.com/embed/playlist/37i9dQZF1DX3fRquEp6m8D?utm_source=generator');
INSERT INTO PLAYLIST VALUES (002,'ANA_MENA',123456,'https://open.spotify.com/embed/playlist/37i9dQZF1DZ06evO3Jtnqm?utm_source=generator');
INSERT INTO PLAYLIST VALUES (003,'BELEN_AGUILERA',123456,'https://open.spotify.com/embed/playlist/37i9dQZF1DZ06evO35iRfG?utm_source=generator');